pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/<your-username>/devops-monitoring-project.git'
      }
    }
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t <your-dockerhub-username>/devopsapp:v1 .'
      }
    }
    stage('Push Docker Image') {
      steps {
        sh 'docker push <your-dockerhub-username>/devopsapp:v1'
      }
    }
    stage('Deploy Infra') {
      steps {
        sh 'cd terraform && terraform apply -auto-approve'
      }
    }
    stage('Configure Monitoring') {
      steps {
        sh 'ansible-playbook -i inventory.ini ansible/setup.yml'
      }
    }
  }
}
